# Generated by Django 5.1.4 on 2026-02-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="tool_calls",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
